const nameRestaurant = [
  "Matryoshka Delight",
  "Babushka Kitchen",
  "Moscow Munchies",
  "Siberian Spice",
  "Vodka Vittles",
  "Borscht & Bites",
  "Caviar Corner",
  "Kremlin Kuisine",
  "Red Square Bistro",
  "Volga Vista",
  "Ural Utopia",
  "Stroganoff Station",
  "Bear and Birch",
  "Ruble Rendezvous",
  "Blini Bliss",
  "Blue Ocean Bistro",
  "Sunset Cafe",
  "Ocean View Eatery",
  "Sunflower Kitchen",
  "Silver Spoon Restaurant",
  "Moonlight Terrace",
  "Starlight Lounge",
  "Tavern",
  "Spice Avenue Kitchen",
  "Urban Spice Cafe",
];

export default nameRestaurant;
